version: '2'
services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dockers/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8010:80"
    links:
      - db
  redmine:
    image: redmine
    container_name: redmine
    ports:
      - 8080:3000
    environment:
      - REDMINE_DB_MYSQL=db
      - REDMINE_DB_USERNAME=root
      - REDMINE_DB_PASSWORD=root
      - REDMINE_DB_DATABASE=redmine
    links:
      - db
  nginx:
    build: ./dockers/nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./:/app
    links:
      - php
      - php-7.0
  # last version of php
  php:
    build: ./dockers/php
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    links:
      - db
  # for magento http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html
  # php version 7.0.*
  php-7.0:
    build: ./dockers/php-7.0
    container_name: php-7.0
    ports:
      - 9001:9000
    volumes:
      - ./:/app
    links:
      - db