version: '2'
services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8010:80"
    links:
      - db
  nginx:
    build: ./dockers/nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./:/app
    links:
      - php
  php:
    build: ./dockers/php
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    links:
      - db